"""Added relations to models.

Revision ID: 02a6b6e116fd
Revises: 5f3e0f72b394
Create Date: 2017-03-25 17:09:07.862216

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '02a6b6e116fd'
down_revision = '5f3e0f72b394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('head_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'departments', 'employees', ['head_id'], ['id'])
    op.add_column('employees', sa.Column('current_employment_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'employees', 'employments', ['current_employment_id'], ['id'])
    op.add_column('employments', sa.Column('department_id', postgresql.UUID(), nullable=False))
    op.add_column('employments', sa.Column('employee_id', postgresql.UUID(), nullable=False))
    op.add_column('employments', sa.Column('position_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'employments', 'employees', ['employee_id'], ['id'])
    op.create_foreign_key(None, 'employments', 'positions', ['position_id'], ['id'])
    op.create_foreign_key(None, 'employments', 'departments', ['department_id'], ['id'])
    op.add_column('vacancies', sa.Column('department_id', postgresql.UUID(), nullable=False))
    op.add_column('vacancies', sa.Column('position_id', postgresql.UUID(), nullable=True))
    op.create_foreign_key(None, 'vacancies', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'vacancies', 'positions', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_constraint(None, 'vacancies', type_='foreignkey')
    op.drop_column('vacancies', 'position_id')
    op.drop_column('vacancies', 'department_id')
    op.drop_constraint(None, 'employments', type_='foreignkey')
    op.drop_constraint(None, 'employments', type_='foreignkey')
    op.drop_constraint(None, 'employments', type_='foreignkey')
    op.drop_column('employments', 'position_id')
    op.drop_column('employments', 'employee_id')
    op.drop_column('employments', 'department_id')
    op.drop_constraint(None, 'employees', type_='foreignkey')
    op.drop_column('employees', 'current_employment_id')
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.drop_column('departments', 'head_id')
    # ### end Alembic commands ###
